### PR TITLE
Update the acknowledgements for old translations repo

### PR DESCRIPTION
**Pull request by rexwangcc**
### Purpose

- As discussed offline, update the acknowledgements for translation contributors. (inspired by https://github.com/SpaceVim/SpaceVim#support-spacevim and https://github.com/vuejs/vuepress/blob/master/README.md#code-contributors layouts) I wrote a script to generate the svg for ANY repo using Github API. If it looks good to you, maybe we could consider integrate it to the main repo as well and set up a Cron job?

### Changes

- Add the contrib atlas svg of taichi-docs-zh-cn.
- Update the acknowledgements for old translations repo.

### Review Instructions

- The readme won't render properly until the PR is merged, you could either download the SVG to view it locally, or view my screenshot:

Screen Shot 2021-04-07 at 11 23 12 PM

### CODE REVIEW

**Review by yuanming-hu — APPROVED** [review]
Wow, this looks so nice!! Thank you :-)

**Comment by rexwangcc** [comment]
> Wow, this looks so nice!! Thank you :-)

Thanks for the prompt reply ! I'll make the script as a Github Action and create a cron job to update the SVG regularly. The generated SVG for the main repo looks good too, maybe we could put it in the main repo as well?

Screen Shot 2021-04-08 at 10 46 40 PM

**Comment by yuanming-hu** [comment]
Yeah, this looks nice! @k-ye and I are indeed considering updating the main repo `README`. Would it be possible to create an SVG with all the [61 contributors](https://github.com/taichi-dev/taichi/graphs/contributors)? Once we have the SVG/PNG file we will post it together with our `README` update :-) We can put the PNG file in this repo (or another repo with just this image) and include a link in the main repo, to avoid the main repo becoming too large. Then the cron job regularly regenerates the image. The website can refer to the URL for this image too. WDYT?

**Comment by rexwangcc** [comment]
> Would it be possible to create an SVG with all the [61 contributors](https://github.com/taichi-dev/taichi/graphs/contributors)?

Yes! It turns out the [Github API endpoint](https://docs.github.com/en/rest/reference/repos#list-repository-contributors) I was using had a pagination parameter which I omitted previously. After fixing it the SVG looks like:

Screen Shot 2021-04-08 at 11 32 36 PM

Which currently has all of the 60 contributors. (there are indeed 69 in total, but 9 of them are anonymous users, and it's impossible to pull avatars of them due to Github privacy policy)

> We can put the PNG file in this repo (or another repo with just this image) and include a link in the main repo, to avoid the main repo becoming too large. Then the cron job regularly regenerates the image.

That is a great idea! I also prefer we put them in a standalone repo with only assets shared across the org and Github actions (that updates the assets or perform other cron tasks).

> The website can refer to the URL for this image too.

Totally makes sense. I think we can even use a CDN to avoid github rate limits, such as `https://www.jsdelivr.com/`. An example could be:

```
https://cdn.jsdelivr.net/gh/taichi-dev/taichi.graphics@master/assets/contributors_taichi-dev_taichi-docs-zh-cn_12.svg
```

[](https://github.com/taichi-dev/taichi-docs-zh-cn/graphs/contributors)

which links to the contributions page.

When it comes to the layout, I'm parameterizing the num per row and avatar size so we could fine tune them for each repo depends on the scale of contributors.

**Comment by yuanming-hu** [comment]
Sounds like a plan! https://github.com/taichi-dev/public_files might be the repo you are looking for :-)

**Pull request merged**
